services:
  # Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ${WEB_DIRECTORY}:/var/www/
      - ./services/nginx/sites-enabled:/etc/nginx/conf.d/
    depends_on:
      - php74
      - php81
      - php84
      - mysql8
    networks:
      - app-network

  # PHP
  php74:
    build:
      context: ./services/php-fpm
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=7.4-fpm
        - INSTALL_COMPOSER=true
    container_name: php74
    working_dir: /var/www
    volumes:
      - ${WEB_DIRECTORY}:/var/www/
      - ./services/php-fpm/config/php7.4.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  php81:
    build:
      context: ./services/php-fpm
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.1-fpm-alpine
        - INSTALL_COMPOSER=true
    container_name: php81
    working_dir: /var/www
    volumes:
      - ${WEB_DIRECTORY}:/var/www/
      - ./services/php-fpm/config/php8.1.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  php84:
    build:
      context: ./services/php-fpm
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.4-fpm-alpine
        - INSTALL_COMPOSER=true
    container_name: php84
    working_dir: /var/www
    volumes:
      - ${WEB_DIRECTORY}:/var/www/
      - ./services/php-fpm/config/php8.4.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  node:
    image: node:20-alpine
    container_name: node
    working_dir: /var/www
    volumes:
      - ${WEB_DIRECTORY}:/var/www
    command: sh -c "node -v && tail -f /dev/null"
    networks:
      - app-network

  # MySQL 8 Service
  mysql8:
    image: mysql:8
    container_name: mysql8
    ports:
      - "4406:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql8_data:/var/lib/mysql
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Python Real Estate Price Predictor Service
  # real-estate-price:
  #   build:
  #     context: ../real-estate-price-predictor
  #   container_name: real-estate-price
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  #   volumes:
  #     - ../real-estate-price-predictor:/app
  #   expose:
  #     - "8000"
  #   networks:
  #     - app-network

  # Golang API Service
  # golang-api:
  #   build:
  #     context: ../golang-api
  #     dockerfile: Dockerfile
  #   container_name: golang-api
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ../golang-api:/app
  #   depends_on:
  #     mysql8:
  #       condition: service_started
  #     rabbitmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  #   networks:
  #     - app-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ with dashboard
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # port AMQP
      - "15672:15672" # port dashboard web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql8_data:
  postgres_data:
  redis_data:
  rabbitmq_data:
  elasticsearch_data:
