#!/bin/bash

# stop docker
docker compose stop

status2=$(docker images -f "dangling=true" -q | wc -l)
# Delete all none images
if [ $status2 -gt 0 ]; then
    echo "images not empty, removing them..."
    docker rmi $(docker images -f "dangling=true" -q)
    echo "done"
fi

# rebuild dan start container
docker compose up --build -d

# cek status container
docker compose ps